/* START QUERY BUILDER */
EVALUATE
SELECTCOLUMNS(
    FILTER(
        SUMMARIZECOLUMNS(
            Model_data[home_encoded],
            Model_data[away_encoded],  
            Model_data[Date],
            Model_data[home_team_name],
            Model_data[away_team_name],
            Model_data[venue_encoded],
            Model_data[venue_capacity],  
            Model_data[venue_grass], 
            Model_data[venue_name],  
            Model_data[league_encoded],  
            Model_data[league_id],
            Model_data[league_name], 
            Model_data[league_season], 
            Model_data[match_outcome],
            Model_data[referee],  
            Model_data[referee_encoded], 
            Model_data[away_attack_strength], 
            Model_data[away_average_points],
            Model_data[away_ball_possession_accuracy], 
            Model_data[away_corners_mean],
            Model_data[away_corners_rollingaverage], 
            Model_data[away_defense_weakness],
            Model_data[away_draw_rate],
            Model_data[Away_draws],
            Model_data[away_form_momentum],
            Model_data[Away_fouls_mean],
            Model_data[away_fouls_rollingaverage],
            Model_data[Away_goal_difference_cum],
            Model_data[away_goal_difference_rollingaverage],
            Model_data[away_goal_rollingaverage],
            Model_data[away_goals],
            Model_data[away_h2h_dominance],
            Model_data[away_h2h_wins],
            Model_data[away_league_position],
            Model_data[Away_offsides_mean],
            Model_data[Away_passes_mean],
            Model_data[away_points],
            Model_data[Away_points_cum],
            Model_data[away_possession_mean],
            Model_data[away_red_cards_mean],
            Model_data[away_red_cards_rollingaverage],
            Model_data[Away_saves_mean],
            Model_data[away_saves_rollingaverage],
            Model_data[away_set_piece_threat],
            Model_data[away_shot_on_target_mean],
            Model_data[away_shot_on_target_rollingaverage],
            Model_data[away_shots_on_target_accuracy_rollingaverage],
            Model_data[Away_team_matches],
            Model_data[away_win],
            Model_data[away_win_rate],
            Model_data[Away_wins],
            Model_data[away_xG_rolling_rollingaverage],
            Model_data[away_yellow_cards_mean],
            Model_data[away_yellow_cards_rollingaverage],
            Model_data[AwayTeam_last_home_match],
            Model_data[draw],
            Model_data[fixture_id],
            Model_data[h2h_avg_goals],
            Model_data[h2h_draws], 
            Model_data[h2h_matches],
            Model_data[home_attack_strength],
            Model_data[home_average_points],
            Model_data[home_corners_mean],
            Model_data[home_corners_rollingaverage],
            Model_data[home_defense_weakness],
            Model_data[home_draw_rate],
            Model_data[Home_draws],
            Model_data[home_form_momentum],
            Model_data[Home_fouls_mean],
            Model_data[home_fouls_rollingaverage],
            Model_data[Home_goal_difference_cum],
            Model_data[home_goal_difference_rollingaverage],
            Model_data[home_goal_rollingaverage],
            Model_data[home_goals],
            Model_data[home_h2h_dominance],
            Model_data[home_h2h_wins],
            Model_data[home_league_position],
            Model_data[Home_offsides_mean],
            Model_data[Home_passes_mean],
            Model_data[home_points],
            Model_data[Home_points_cum],
            Model_data[Home_possession_mean],
            Model_data[home_red_cards_mean],
            Model_data[home_red_cards_rollingaverage],
            Model_data[Home_saves_mean],
            Model_data[home_saves_rollingaverage],
            Model_data[home_set_piece_threat],
            Model_data[Home_shot_on_target_mean],
            Model_data[home_shot_on_target_rollingaverage],
            Model_data[home_shots_on_target_accuracy_rollingaverage],
            Model_data[Home_team_matches],
            Model_data[home_win],
            Model_data[home_win_rate],
            Model_data[Home_wins],
            Model_data[home_xG_rolling_rollingaverage],
            Model_data[home_yellow_cards_mean],
            Model_data[home_yellow_cards_rollingaverage],
            Model_data[HomeTeam_last_away_match],
            Model_data[referee_foul_rate],
            Model_data[home_founded_year],
            Model_data[away_founded_year],
            Model_data[season_encoded],
            Model_data[Season_league],
            Model_data[venue_id]   
        ),
        Model_data[away_average_points] >= 0
    ),
    "home_encoded", ROUNDUP(Model_data[home_encoded], 0),
    "away_encoded", ROUNDUP(Model_data[away_encoded], 0),
    "Date", Model_data[Date],
    "home_team_name", Model_data[home_team_name],
    "away_team_name", Model_data[away_team_name],
    "venue_encoded", ROUNDUP(Model_data[venue_encoded], 0),
    "venue_capacity", ROUNDUP(Model_data[venue_capacity], 0),
    "venue_grass", ROUNDUP(Model_data[venue_grass], 0),
    "venue_name", Model_data[venue_name],
    "league_encoded", ROUNDUP(Model_data[league_encoded], 0),
    "league_id", ROUNDUP(Model_data[league_id], 0),
    "league_name", Model_data[league_name],
    "league_season", Model_data[league_season],
    "match_outcome", Model_data[match_outcome],
    "referee", Model_data[referee], 
    "referee_encoded", ROUNDUP(Model_data[referee_encoded], 0),
    "away_attack_strength", ROUNDUP(Model_data[away_attack_strength], 2),
    "away_average_points", ROUNDUP(Model_data[away_average_points], 2),
    "away_ball_possession_accuracy", ROUNDUP(Model_data[away_ball_possession_accuracy], 2),
    "away_corners_mean", ROUNDUP(Model_data[away_corners_mean], 2),
    "away_corners_rollingaverage", ROUNDUP(Model_data[away_corners_rollingaverage], 2),
    "away_defense_weakness", ROUNDUP(Model_data[away_defense_weakness], 2),
    "away_draw_rate", ROUNDUP(Model_data[away_draw_rate], 2),
    "Away_draws", ROUNDUP(Model_data[Away_draws], 2),
    "away_form_momentum", ROUNDUP(Model_data[away_form_momentum], 2),
    "Away_fouls_mean", ROUNDUP(Model_data[Away_fouls_mean], 2),
    "away_fouls_rollingaverage", ROUNDUP(Model_data[away_fouls_rollingaverage], 2),
    "Away_goal_difference_cum", ROUNDUP(Model_data[Away_goal_difference_cum], 2),
    "away_goal_difference_rollingaverage", ROUNDUP(Model_data[away_goal_difference_rollingaverage], 2),
    "away_goal_rollingaverage", ROUNDUP(Model_data[away_goal_rollingaverage], 2),
    "away_goals", ROUNDUP(Model_data[away_goals], 2),
    "away_h2h_dominance", ROUNDUP(Model_data[away_h2h_dominance], 2),
    "away_h2h_wins", ROUNDUP(Model_data[away_h2h_wins], 2),
    "away_league_position", ROUNDUP(Model_data[away_league_position], 2),
    "Away_offsides_mean", ROUNDUP(Model_data[Away_offsides_mean], 2),
    "Away_passes_mean", ROUNDUP(Model_data[Away_passes_mean], 2),
    "away_points", ROUNDUP(Model_data[away_points], 2),
    "Away_points_cum", ROUNDUP(Model_data[Away_points_cum], 2),
    "away_possession_mean", ROUNDUP(Model_data[away_possession_mean], 2),
    "away_red_cards_mean", ROUNDUP(Model_data[away_red_cards_mean], 2),
    "away_red_cards_rollingaverage", ROUNDUP(Model_data[away_red_cards_rollingaverage], 2),
    "Away_saves_mean", ROUNDUP(Model_data[Away_saves_mean], 2),
    "away_saves_rollingaverage", ROUNDUP(Model_data[away_saves_rollingaverage], 2),
    "away_set_piece_threat", ROUNDUP(Model_data[away_set_piece_threat], 2),
    "away_shot_on_target_mean", ROUNDUP(Model_data[away_shot_on_target_mean], 2),
    "away_shot_on_target_rollingaverage", ROUNDUP(Model_data[away_shot_on_target_rollingaverage], 2),
    "away_shots_on_target_accuracy_rollingaverage", ROUNDUP(Model_data[away_shots_on_target_accuracy_rollingaverage], 2),
    "Away_team_matches", ROUNDUP(Model_data[Away_team_matches], 2),
    "away_win", ROUNDUP(Model_data[away_win], 2),
    "away_win_rate", ROUNDUP(Model_data[away_win_rate], 2),
    "Away_wins", ROUNDUP(Model_data[Away_wins], 2),
    "away_xG_rolling_rollingaverage", ROUNDUP(Model_data[away_xG_rolling_rollingaverage], 2),
    "away_yellow_cards_mean", ROUNDUP(Model_data[away_yellow_cards_mean], 2),
    "away_yellow_cards_rollingaverage", ROUNDUP(Model_data[away_yellow_cards_rollingaverage], 2),
    "AwayTeam_last_home_match", ROUNDUP(Model_data[AwayTeam_last_home_match], 2),
    "draw", ROUNDUP(Model_data[draw], 2),
    "fixture_id", ROUNDUP(Model_data[fixture_id], 2),
    "h2h_avg_goals", ROUNDUP(Model_data[h2h_avg_goals], 2),
    "h2h_draws", ROUNDUP(Model_data[h2h_draws], 2),
    "h2h_matches", ROUNDUP(Model_data[h2h_matches], 2),
    "home_attack_strength", ROUNDUP(Model_data[home_attack_strength], 2),
    "home_average_points", ROUNDUP(Model_data[home_average_points], 2),
    "home_corners_mean", ROUNDUP(Model_data[home_corners_mean], 2),
    "home_corners_rollingaverage", ROUNDUP(Model_data[home_corners_rollingaverage], 2),
    "home_defense_weakness", ROUNDUP(Model_data[home_defense_weakness], 2),
    "home_draw_rate", ROUNDUP(Model_data[home_draw_rate], 2),
    "Home_draws", ROUNDUP(Model_data[Home_draws], 2),
    "home_form_momentum", ROUNDUP(Model_data[home_form_momentum], 2),
    "Home_fouls_mean", ROUNDUP(Model_data[Home_fouls_mean], 2),
    "home_fouls_rollingaverage", ROUNDUP(Model_data[home_fouls_rollingaverage], 2),
    "Home_goal_difference_cum", ROUNDUP(Model_data[Home_goal_difference_cum], 2),
    "home_goal_difference_rollingaverage", ROUNDUP(Model_data[home_goal_difference_rollingaverage], 2),
    "home_goal_rollingaverage", ROUNDUP(Model_data[home_goal_rollingaverage], 2),
    "home_goals", ROUNDUP(Model_data[home_goals], 2),
    "home_h2h_dominance", ROUNDUP(Model_data[home_h2h_dominance], 2),
    "home_h2h_wins", ROUNDUP(Model_data[home_h2h_wins], 2),
    "home_league_position", ROUNDUP(Model_data[home_league_position], 2),
    "Home_offsides_mean", ROUNDUP(Model_data[Home_offsides_mean], 2),
    "Home_passes_mean", ROUNDUP(Model_data[Home_passes_mean], 2),
    "home_points", ROUNDUP(Model_data[home_points], 2),
    "Home_points_cum", ROUNDUP(Model_data[Home_points_cum], 2),
    "Home_possession_mean", ROUNDUP(Model_data[Home_possession_mean], 2),
    "home_red_cards_mean", ROUNDUP(Model_data[home_red_cards_mean], 2),
    "home_red_cards_rollingaverage", ROUNDUP(Model_data[home_red_cards_rollingaverage], 2),
    "Home_saves_mean", ROUNDUP(Model_data[Home_saves_mean], 2),
    "home_saves_rollingaverage", ROUNDUP(Model_data[home_saves_rollingaverage], 2),
    "home_set_piece_threat", ROUNDUP(Model_data[home_set_piece_threat], 2),
    "Home_shot_on_target_mean", ROUNDUP(Model_data[Home_shot_on_target_mean], 2),
    "home_shot_on_target_rollingaverage", ROUNDUP(Model_data[home_shot_on_target_rollingaverage], 2),
    "home_shots_on_target_accuracy_rollingaverage", ROUNDUP(Model_data[home_shots_on_target_accuracy_rollingaverage], 2),
    "Home_team_matches", ROUNDUP(Model_data[Home_team_matches], 2),
    "home_win", ROUNDUP(Model_data[home_win], 2),
    "home_win_rate", ROUNDUP(Model_data[home_win_rate], 2),
    "Home_wins", ROUNDUP(Model_data[Home_wins], 2),
    "home_xG_rolling_rollingaverage", ROUNDUP(Model_data[home_xG_rolling_rollingaverage], 2),
    "home_yellow_cards_mean", ROUNDUP(Model_data[home_yellow_cards_mean], 2),
    "home_yellow_cards_rollingaverage", ROUNDUP(Model_data[home_yellow_cards_rollingaverage], 2),
    "HomeTeam_last_away_match", ROUNDUP(Model_data[HomeTeam_last_away_match], 2),
    "referee_foul_rate", ROUNDUP(Model_data[referee_foul_rate], 2),
    "home_founded_year", ROUNDUP(Model_data[home_founded_year], 2),
    "away_founded_year", ROUNDUP(Model_data[away_founded_year], 2),
    "season_encoded", ROUNDUP(Model_data[season_encoded], 2),
    "Season_league", Model_data[Season_league],
    "venue_id", ROUNDUP(Model_data[venue_id], 2)
)

/* END QUERY BUILDER */