/* START QUERY BUILDER */
EVALUATE
SELECTCOLUMNS(
    FILTER(
        SUMMARIZECOLUMNS(
            future_matches[home_encoded],
            future_matches[away_encoded], 
            future_matches[Datum],
            future_matches[Home],
            future_matches[Away],  
            future_matches[venue_encoded], 
            future_matches[venue_capacity], 
            future_matches[venue_grass],   
            future_matches[venue_name],   
            future_matches[league_name], 
            future_matches[league_encoded],
            future_matches[referee], 
            future_matches[referee_encoded], 
            future_matches[Last_home_match],  
            future_matches[Last_away_match],  
            future_matches[away_attack_strength],
            future_matches[away_average_points],
            future_matches[away_corners_mean],
            future_matches[away_corners_rollingaverage], 
            future_matches[away_defense_weakness],
            future_matches[away_draw_rate],
            future_matches[Away_draws],
            future_matches[away_form_momentum], 
            future_matches[Away_fouls_mean],
            future_matches[away_fouls_rollingaverage],
            future_matches[Away_goal_difference_cum],
            future_matches[away_goal_difference_rollingaverage],
            future_matches[away_goal_rollingaverage],
            future_matches[away_h2h_dominance],
            future_matches[away_h2h_wins],
            future_matches[away_league_position],
            future_matches[Away_offsides_mean],
            future_matches[Away_passes_mean],
            future_matches[Away_points_cum],
            future_matches[away_possession_mean],
            future_matches[away_red_cards_mean],
            future_matches[away_red_cards_rollingaverage],
            future_matches[Away_saves_mean],
            future_matches[away_saves_rollingaverage],
            future_matches[away_shot_on_target_mean],
            future_matches[away_shot_on_target_rollingaverage],
            future_matches[away_shots_on_target_accuracy_rollingaverage],
            future_matches[Away_team_matches],
            future_matches[away_win_rate],
            future_matches[Away_wins],
            future_matches[away_xG_rolling_rollingaverage],
            future_matches[away_yellow_cards_mean],
            future_matches[away_yellow_cards_rollingaverage],
            future_matches[fixture_id],
            future_matches[h2h_avg_goals],
            future_matches[h2h_draws], 
            future_matches[h2h_matches],
            future_matches[home_attack_strength],
            future_matches[home_average_points],
            future_matches[home_corners_mean],
            future_matches[home_corners_rollingaverage],
            future_matches[home_defense_weakness],
            future_matches[home_draw_rate],
            future_matches[Home_draws],
            future_matches[home_form_momentum],
            future_matches[Home_fouls_mean],
            future_matches[home_fouls_rollingaverage],
            future_matches[Home_goal_difference_cum],
            future_matches[home_goal_difference_rollingaverage],
            future_matches[home_goal_rollingaverage],
            future_matches[home_h2h_dominance],
            future_matches[home_h2h_wins],
            future_matches[home_league_position],
            future_matches[Home_offsides_mean],
            future_matches[Home_passes_mean],
            future_matches[Home_points_cum],
            future_matches[Home_possession_mean],
            future_matches[home_red_cards_mean],
            future_matches[home_red_cards_rollingaverage],
            future_matches[Home_saves_mean],
            future_matches[home_saves_rollingaverage],
            future_matches[Home_shot_on_target_mean],
            future_matches[home_shot_on_target_rollingaverage],
            future_matches[home_shots_on_target_accuracy_rollingaverage],
            future_matches[Home_team_matches],
            future_matches[home_win_rate],
            future_matches[Home_wins],
            future_matches[home_xG_rolling_rollingaverage],
            future_matches[home_yellow_cards_mean],
            future_matches[home_yellow_cards_rollingaverage],
            future_matches[referee_foul_rate],
            future_matches[home_founded_year],
            future_matches[away_founded_year],
            future_matches[season_encoded],
            future_matches[Season_league]
        ),
        future_matches[away_average_points] <> BLANK() && future_matches[away_average_points] >= 0 
        || future_matches[Away_fouls_mean] <> BLANK() &&  future_matches[away_average_points] >= 0 
    ),
    "home_encoded", ROUNDUP(future_matches[home_encoded], 0),
    "away_encoded", ROUNDUP(future_matches[away_encoded], 0),
    "Date", future_matches[Datum],
    "Home", future_matches[Home],
    "Away", future_matches[Away],
    "venue_encoded", ROUNDUP(future_matches[venue_encoded], 0),
    "venue_capacity", ROUNDUP(future_matches[venue_capacity], 0),
    "venue_grass", ROUNDUP(future_matches[venue_grass], 0),
    "venue_name", future_matches[venue_name],
    "league_encoded", ROUNDUP(future_matches[league_encoded], 0),
    "league_name", future_matches[league_name], 
    "referee", future_matches[referee],
    "Last_home_match",future_matches[Last_home_match],
    "Last_away_match",future_matches[Last_away_match],
    "referee_encoded", ROUNDUP(future_matches[referee_encoded], 0),
    "away_attack_strength", ROUNDUP(future_matches[away_attack_strength], 2),
    "away_average_points", ROUNDUP(future_matches[away_average_points], 2),
    "away_corners_mean", ROUNDUP(future_matches[away_corners_mean], 2),
    "away_corners_rollingaverage", ROUNDUP(future_matches[away_corners_rollingaverage], 2),
    "away_defense_weakness", ROUNDUP(future_matches[away_defense_weakness], 2),
    "away_draw_rate", ROUNDUP(future_matches[away_draw_rate], 2),
    "Away_draws", ROUNDUP(future_matches[Away_draws], 2),
    "away_form_momentum", ROUNDUP(future_matches[away_form_momentum], 2),
    "Away_fouls_mean", ROUNDUP(future_matches[Away_fouls_mean], 2),
    "away_fouls_rollingaverage", ROUNDUP(future_matches[away_fouls_rollingaverage], 2),
    "Away_goal_difference_cum", ROUNDUP(future_matches[Away_goal_difference_cum], 2),
    "away_goal_difference_rollingaverage", ROUNDUP(future_matches[away_goal_difference_rollingaverage], 2),
    "away_goal_rollingaverage", ROUNDUP(future_matches[away_goal_rollingaverage], 2),
    "away_h2h_dominance", ROUNDUP(future_matches[away_h2h_dominance], 2),
    "away_h2h_wins", ROUNDUP(future_matches[away_h2h_wins], 2),
    "away_league_position", ROUNDUP(future_matches[away_league_position], 2),
    "Away_offsides_mean", ROUNDUP(future_matches[Away_offsides_mean], 2),
    "Away_passes_mean", ROUNDUP(future_matches[Away_passes_mean], 2),
  
    "Away_points_cum", ROUNDUP(future_matches[Away_points_cum], 2),
    "away_possession_mean", ROUNDUP(future_matches[away_possession_mean], 2),
    "away_red_cards_mean", ROUNDUP(future_matches[away_red_cards_mean], 2),
    "away_red_cards_rollingaverage", ROUNDUP(future_matches[away_red_cards_rollingaverage], 2),
    "Away_saves_mean", ROUNDUP(future_matches[Away_saves_mean], 2),
    "away_saves_rollingaverage", ROUNDUP(future_matches[away_saves_rollingaverage], 2),
    "away_shot_on_target_mean", ROUNDUP(future_matches[away_shot_on_target_mean], 2),
    "away_shot_on_target_rollingaverage", ROUNDUP(future_matches[away_shot_on_target_rollingaverage], 2),
    "away_shots_on_target_accuracy_rollingaverage", ROUNDUP(future_matches[away_shots_on_target_accuracy_rollingaverage], 2),
    "Away_team_matches", ROUNDUP(future_matches[Away_team_matches], 2),

    "away_win_rate", ROUNDUP(future_matches[away_win_rate], 2),
    "Away_wins", ROUNDUP(future_matches[Away_wins], 2),
    "away_xG_rolling_rollingaverage", ROUNDUP(future_matches[away_xG_rolling_rollingaverage], 2),
    "away_yellow_cards_mean", ROUNDUP(future_matches[away_yellow_cards_mean], 2),
    "away_yellow_cards_rollingaverage", ROUNDUP(future_matches[away_yellow_cards_rollingaverage], 2),

    
    "fixture_id", ROUNDUP(future_matches[fixture_id], 2),
    "h2h_avg_goals", ROUNDUP(future_matches[h2h_avg_goals], 2),
    "h2h_draws", ROUNDUP(future_matches[h2h_draws], 2),
    "h2h_matches", ROUNDUP(future_matches[h2h_matches], 2),
    "home_attack_strength", ROUNDUP(future_matches[home_attack_strength], 2),
    "home_average_points", ROUNDUP(future_matches[home_average_points], 2),
    "home_corners_mean", ROUNDUP(future_matches[home_corners_mean], 2),
    "home_corners_rollingaverage", ROUNDUP(future_matches[home_corners_rollingaverage], 2),
    "home_defense_weakness", ROUNDUP(future_matches[home_defense_weakness], 2),
    "home_draw_rate", ROUNDUP(future_matches[home_draw_rate], 2),
    "Home_draws", ROUNDUP(future_matches[Home_draws], 2),
    "home_form_momentum", ROUNDUP(future_matches[home_form_momentum], 2),
    "Home_fouls_mean", ROUNDUP(future_matches[Home_fouls_mean], 2),
    "home_fouls_rollingaverage", ROUNDUP(future_matches[home_fouls_rollingaverage], 2),
    "Home_goal_difference_cum", ROUNDUP(future_matches[Home_goal_difference_cum], 2),
    "home_goal_difference_rollingaverage", ROUNDUP(future_matches[home_goal_difference_rollingaverage], 2),
    "home_goal_rollingaverage", ROUNDUP(future_matches[home_goal_rollingaverage], 2),

    "home_h2h_dominance", ROUNDUP(future_matches[home_h2h_dominance], 2),
    "home_h2h_wins", ROUNDUP(future_matches[home_h2h_wins], 2),
    "home_league_position", ROUNDUP(future_matches[home_league_position], 2),
    "Home_offsides_mean", ROUNDUP(future_matches[Home_offsides_mean], 2),
    "Home_passes_mean", ROUNDUP(future_matches[Home_passes_mean], 2),
  
    "Home_points_cum", ROUNDUP(future_matches[Home_points_cum], 2),
    "Home_possession_mean", ROUNDUP(future_matches[Home_possession_mean], 2),
    "home_red_cards_mean", ROUNDUP(future_matches[home_red_cards_mean], 2),
    "home_red_cards_rollingaverage", ROUNDUP(future_matches[home_red_cards_rollingaverage], 2),
    "Home_saves_mean", ROUNDUP(future_matches[Home_saves_mean], 2),
    "home_saves_rollingaverage", ROUNDUP(future_matches[home_saves_rollingaverage], 2),
    "Home_shot_on_target_mean", ROUNDUP(future_matches[Home_shot_on_target_mean], 2),
    "home_shot_on_target_rollingaverage", ROUNDUP(future_matches[home_shot_on_target_rollingaverage], 2),
    "home_shots_on_target_accuracy_rollingaverage", ROUNDUP(future_matches[home_shots_on_target_accuracy_rollingaverage], 2),
    "Home_team_matches", ROUNDUP(future_matches[Home_team_matches], 2),
    
    "home_win_rate", ROUNDUP(future_matches[home_win_rate], 2),
    "Home_wins", ROUNDUP(future_matches[Home_wins], 2),
    "home_xG_rolling_rollingaverage", ROUNDUP(future_matches[home_xG_rolling_rollingaverage], 2),
    "home_yellow_cards_mean", ROUNDUP(future_matches[home_yellow_cards_mean], 2),
    "home_yellow_cards_rollingaverage", ROUNDUP(future_matches[home_yellow_cards_rollingaverage], 2),
    "referee_foul_rate", ROUNDUP(future_matches[referee_foul_rate], 2),
    "home_founded_year", ROUNDUP(future_matches[home_founded_year], 2),
    "away_founded_year", ROUNDUP(future_matches[away_founded_year], 2),
    "season_encoded", ROUNDUP(future_matches[season_encoded], 2),
    "Season_league", future_matches[Season_league]
)

/* END QUERY BUILDER */