name: soccerpredictor_env
channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - python=3.9.15
  - pip
  
  # Core ML Stack
  - xgboost=2.1.3=cpu_pyhc1a9e11_1
  - catboost=1.2.7
  - lightgbm=4.5.0
  - mlflow=2.11.3
  - optuna=3.6.1
  - pycaret=3.3.2
  
  # Data Processing
  - pandas=2.0.3
  - numpy=1.23.5
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - openpyxl=3.1.2
  
  # Feature Engineering
  - feature-engine=1.6.1
  - category_encoders=2.6.4
  - imbalanced-learn=0.12.2
  
  # Hyperparameter Tuning
  - optuna=3.6.1
  - hyperopt=0.2.7
  
  # Visualization
  - matplotlib=3.7.1
  - plotly=5.18.0
  - seaborn=0.13.2
  
  # CPU-only Deep Learning
  - tensorflow=2.10.0=cpu_py39h6a7f48e_0
  - pytorch=2.0.1=cpu_py39h7cc8b2b_0
  - torchvision=0.15.2=cpu_py39h8871c0c_0
  
  # Utilities
  - tqdm=4.66.1
  - joblib=1.3.2
  - psutil=5.9.5
  - pyyaml=6.0.1
  
  # Environment Config
  - pip:
    - autofeat==2.1.3
    - causalnex==0.12.1
    - lxml==5.3.0
    - bandit==1.8.0
    - coverage==7.6.9
    - pytest-cov==6.0.0
    - vulture==2.14
    - wandb==0.19.2
    - lifelines==0.28.0
    - build==1.2.2.post1
    - pycurl==7.45.4
    - keras==3.7.0

  # Explicit CPU-only channels
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly 