hyperparameters:
  learning_rate:
    distribution: log_uniform
    min: 0.001
    max: 0.1
    
  num_leaves:
    distribution: int_uniform
    min: 20
    max: 100
    
  min_data_in_leaf:
    distribution: int_uniform
    min: 20
    max: 100
    
  feature_fraction:
    distribution: uniform
    min: 0.6
    max: 1.0
    
  bagging_fraction:
    distribution: uniform
    min: 0.6
    max: 1.0
    
  bagging_freq:
    distribution: int_uniform
    min: 1
    max: 7
    
  lambda_l1:
    distribution: log_uniform
    min: 0.0
    max: 10.0
    
  lambda_l2:
    distribution: log_uniform
    min: 0.0
    max: 10.0
    
  min_gain_to_split:
    distribution: log_uniform
    min: 0.0
    max: 5.0
    
  scale_pos_weight:
    distribution: uniform
    min: 1.0
    max: 5.0

search_strategy:
  name: population_based_training
  settings:
    population_size: 8
    perturbation_interval: 4
    time_attr: training_iteration
    metric: precision
    mode: max
    
  resources:
    cpu_per_trial: 1
    max_concurrent_trials: 4
    
  stopping:
    max_iterations: 100
    target_metrics:
      precision: 0.35
      recall: 0.20
    
  checkpointing:
    frequency: 1
    keep_top_n: 3 