hyperparameters:
  learning_rate:
    distribution: log_uniform
    min: 0.005
    max: 0.03
    
  max_depth:
    distribution: int_uniform
    min: 1
    max: 6
    
  min_child_weight:
    distribution: int_uniform
    min: 100
    max: 200
    
  subsample:
    distribution: uniform
    min: 0.2
    max: 0.5
    
  colsample_bytree:
    distribution: uniform
    min: 0.5
    max: 0.8
    
  gamma:
    distribution: uniform
    min: 0.01
    max: 0.1
    
  lambda:
    distribution: uniform
    min: 5.0
    max: 15.0
    
  alpha:
    distribution: uniform
    min: 0.01
    max: 0.1
    
  scale_pos_weight:
    distribution: uniform
    min: 1.5
    max: 3.0
    
  early_stopping_rounds:
    distribution: int_uniform
    min: 200
    max: 800
    
  n_estimators:
    distribution: int_uniform
    min: 300
    max: 2500
    
  reg_alpha:
    distribution: uniform
    min: 0.01
    max: 0.1
    
  reg_lambda:
    distribution: uniform
    min: 5.0
    max: 15.0

optimization:
  n_trials: 50
  timeout: 72000  # 20 hours
  study_name: xgboost_optimization
  direction: maximize
  metric: precision
  
  pruning:
    enable: true
    n_warmup_steps: 100
    interval: 100
    
  early_stopping:
    enable: true
    patience: 3
    min_delta: 0.01
    
  target_metrics:
    precision: 0.35
    recall: 0.15