hyperparameters:
  learning_rate:
    distribution: log_uniform
    min: 0.005
    max: 0.03
    
  max_depth:
    distribution: int_uniform
    min: 1
    max: 6
    
  min_child_weight:
    distribution: int_uniform
    min: 100
    max: 200
    
  subsample:
    distribution: uniform
    min: 0.2
    max: 0.5
    
  colsample_bytree:
    distribution: uniform
    min: 0.5
    max: 0.8
    
  gamma:
    distribution: uniform
    min: 0.01
    max: 0.1
    
  lambda:
    distribution: uniform
    min: 5.0
    max: 15.0
    
  alpha:
    distribution: uniform
    min: 0.01
    max: 0.1
    
  scale_pos_weight:
    distribution: uniform
    min: 1.5
    max: 3.0
    
  early_stopping_rounds:
    distribution: int_uniform
    min: 200
    max: 800
    
  n_estimators:
    distribution: int_uniform
    min: 300
    max: 2500
    
  reg_alpha:
    distribution: uniform
    min: 0.01
    max: 0.1
    
  reg_lambda:
    distribution: uniform
    min: 5.0
    max: 15.0

search_strategy:
  name: population_based_training
  settings:
    population_size: 8
    perturbation_interval: 4
    time_attr: training_iteration
    metric: precision
    mode: max
    
  hyperparam_mutations:
    learning_rate:
      min: 0.005
      max: 0.03
      scaling: log
    max_depth:
      min: 1
      max: 6
      scaling: linear
    min_child_weight:
      min: 100
      max: 200
      scaling: linear
    subsample:
      min: 0.2
      max: 0.5
      scaling: linear
    colsample_bytree:
      min: 0.5
      max: 0.8
      scaling: linear
    gamma:
      min: 0.01
      max: 0.1
      scaling: linear
    lambda:
      min: 5.0
      max: 15.0
      scaling: linear
    alpha:
      min: 0.01
      max: 0.1
      scaling: linear
    scale_pos_weight:
      min: 1.5
      max: 3.0
      scaling: linear
    early_stopping_rounds:
      min: 200
      max: 800
      scaling: linear
    n_estimators:
      min: 300
      max: 2500
      scaling: linear
    reg_alpha:
      min: 0.01
      max: 0.1
      scaling: linear
    reg_lambda:
      min: 5.0
      max: 15.0
      scaling: linear
  resources:
    cpu_per_trial: 1
    max_concurrent_trials: 6
    
  stopping:
    max_iterations: 400
    target_metrics:
      precision: 0.35
      recall: 0.15
    
  checkpointing:
    frequency: 1
    keep_top_n: 3