name: mcp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=21.0
  - pip:
    # Core dependencies
    - fastapi>=0.68.0,<0.69.0
    - uvicorn>=0.15.0,<0.16.0
    - pydantic>=1.8.0,<2.0.0
    - python-multipart>=0.0.5,<0.1.0
    - aiofiles>=0.7.0,<0.8.0
    - watchdog>=2.1.0,<3.0.0
    # MLflow integration
    - mlflow>=1.20.0,<2.0.0
    # WebSocket support
    - websockets>=10.0,<11.0
    # Utilities
    - python-json-logger>=2.0.0,<3.0.0
    - structlog>=21.1.0,<22.0.0
    # Development
    - black>=21.7b0
    - isort>=5.9.0,<6.0.0
    - flake8>=3.9.0,<4.0.0
    - mypy>=0.910,<1.0.0
    # Testing
    - pytest>=6.2.0,<7.0.0
    - pytest-asyncio>=0.15.0,<0.16.0
    - pytest-cov>=2.12.0,<3.0.0
    - httpx>=0.18.0,<0.19.0 