model:
  name: bert_classifier
  version: "2.1.0"
  experiment_name: bert_experiment
  cpu_config:
    device: cpu
    fp16: False
    fp16_opt_level: O1
    max_grad_norm: 1.0
    num_workers: 4
  logging:
    log_dir: logs/bert
    metrics_tracking:
      - precision
      - recall
      - f1_score
      - auc
      - average_precision
      - brier_score
  params:
    model_name: bert-base-uncased
    num_labels: 2
    problem_type: single_label_classification
    max_seq_length: 256
    per_device_train_batch_size: 16
    gradient_accumulation_steps: 2
    learning_rate: 2e-5
    num_train_epochs: 3
    warmup_ratio: 0.1
    weight_decay: 0.01
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    seed: 19
    use_early_stopping: True
    early_stopping_patience: 3
    early_stopping_threshold: 0.01 